.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "previousui" "1" "2010-05-30" "Previous" "Previous UI"
.SH "NAME"
previousui \- Python/Gtk UI for Previous
.SH "SYNOPSIS"
.B previousui | previousui.py
.RI [options]
.RI  [directory|diskimage|program]
.SH "DESCRIPTION"
.I previousui
is a Python/Gtk UI for Previous which can either embed the Previous window
(on X11 systems) or run in a separate window.  By default it provides
a normal application menu and some extra button for faster access to
fast\-forward etc. functionality, but these are fully configurable
with the command line options. While it lacks support for some of
the Previous configuration options that Previous's SDL GUI has, it also
supports some options that the Previous's built\-in SDL UI doesn't.
.PP
Besides the UI configurability, some of the other advantages previousui has
over the SDL interface included with Previous itself are use of a normal
Gtk file selector with all of its features (directory shortcuts etc),
support for UTF\-8 (in file names) and in general blending better to
the user's desktop environment.
.PP
Additionally, Previous can run while one uses UI configuration dialogs,
and it can stop Previous completely to better save the battery on mobile
computers.  For devices without a keyboard, it offers a a text input
dialog and one can configure (from command line) buttons for often used
strings.
.SH "HATARIUI / HATARIUI.PY"
.I previousui
is actually a shell script wrapper for the previousui.py Python script.
It's used to run the Python script with suitable options for default
usage and to set up the correct installation directory for the rest
of the Previous UI Python scripts and data files.
.PP
Options below are actually for previousui.py script.  If you want to
change options given for it, modify the previousui shell script or
make your own based on the installed one.
.\" following command line helps in updating the options:
.\" previousui.py --help|sed -e 's/^\t\+/.TP\n.B /' -e 's/\t\+/\n/g' -e 's/-/\\-/g' >> previousui.1
.SH "OPTIONS"
.TP
.B \-h, \-\-help
Previous UI command line help
.TP
.B \-n, \-\-nomenu
Omit menubar from the window
.TP
.B \-e, \-\-embed
Embed Previous window (to middle of controls)
.TP
.B \-f, \-\-fullscreen
Start in fullscreen
.TP
.B \-l, \-\-left <controls>
Add a toolbar at left
.TP
.B \-r, \-\-right <controls>
Add a toolbar at right
.TP
.B \-t, \-\-top <controls>
Add a toolbar at top
.TP
.B \-b, \-\-bottom <controls>
Add a toolbar at bottom
.TP
.B \-p, \-\-panel <name>,<controls>
Add a separate window with given name and controls
.PP
You can have only one toolbar on each side of the Previous window.
Panels are separate windows and you can has as many of them as you wish.
For each panel you need to add a control with the name of the panel
(see "MyPanel" in examples).
.PP
Following controls can are available for toolbars and panels:
.TP
.B |
Separator between controls
.TP
.B >
Next toolbar in panel windows
.TP
.B compatibility
Previous compatibility list
.TP
.B harddisk
Hard disk images and directories
.TP
.B reset
Warm or cold reset Previous
.TP
.B sconfig
Save configuration
.TP
.B bugs
Report a bug
.TP
.B display
Display settings
.TP
.B authors
Previous authors
.TP
.B forward
Whether to fast forward Previous (needs fast machine)
.TP
.B debug
Activate Previous debugger
.TP
.B quit
Quit Previous UI
.TP
.B previous
Previous home page
.TP
.B recanim
Record animation
.TP
.B recsound
Record YM/Wav
.TP
.B mails
Previous mailing lists
.TP
.B floppy
Floppy images
.TP
.B device
Toggle Midi, Printer, RS232 peripherals
.TP
.B load
Load emulation snapshot
.TP
.B lconfig
Load configuration
.TP
.B path
Device & save file paths
.TP
.B machine
Previous st/e/tt/falcon configuration
.TP
.B todo
Previous TODO
.TP
.B previousui
Previous UI home page
.TP
.B save
Save emulation snapshot
.TP
.B joystick
Joystick settings
.TP
.B trace
Previous tracing setup
.TP
.B pause
Pause Previous to save battery
.TP
.B about
Previous UI information
.TP
.B release
Previous release notes
.TP
.B full
Toggle whether Previous is fullscreen
.TP
.B manual
Previous manual
.TP
.B input
Simulate text input and mouse clicks
.TP
.B sound
Sound settings
.TP
.B changes
Latest Previous changes
.TP
.B run
(Re\-)run Previous
.TP
.B shot
Grab a screenshot
.TP
.B <panel name>
Button for the specified panel window
.TP
.B <name>=<string/code>
Synthetize string or single key <code>
.PP
If no options are given, the UI uses basic controls.
.SH "EXAMPLES"
Example on how to add top, right and bottom toolbars and a separate
"MyPanel" panel window:
.nf
	previousui.py \-\-embed \\
	\-t "about,run,pause,quit" \\
	\-p "MyPanel,Macro=Test,Undo=97,Help=98,>,F1=59,F2=60,>,close" \\
	\-r "paste,debug,trace,machine,MyPanel" \\
	\-b "sound,|,forward,|,fullscreen"
.fi
.PP
For more examples on Previous UI options usage, see the previousui shell
script.
.SH "SEE ALSO"
.IR hmsa (1),
.IR previousui (1),
.IR hconsole (1)
.SH "COPYRIGHT"
Previous UI is written by Eero Tamminen <eerot@berlios.de>.
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.
