# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wjk/Code/Previous-tweaks/previous-code/src/ditool/CMakeLists.txt))

/Users/wjk/Code/Previous-tweaks/previous-code/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.27.2/bin/cmake -S/Users/wjk/Code/Previous-tweaks/previous-code -B/Users/wjk/Code/Previous-tweaks/previous-code
