name: Sync SVN with GitHub

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 2 * * MON' # Run every Monday at 2:00 AM

jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2

      - name: Set up Subversion
        run: sudo apt-get install -y subversion
        
      - name: Install SDL2 Library
        run: sudo apt-get install -y libsdl2-dev

  - name: Remove previous working directory
    run: rm -rf /home/runner/work/Previous/Previous/previous-code/
        
      - name: Pull Changes from SVN
        run: |
          svn checkout https://svn.code.sf.net/p/previous/code/trunk previous-code
          cd previous-code
          svn log -r HEAD

      - name: Copy SVN changes to GitHub Repository
        run: |
          cp -r previous-code/* .
          git config --global user.name "itomato"
          git config --global user.email "itomato@juddy.org"
          git add .
          git commit -m "Sync with SVN" || echo "No changes to commit"
          git push origin master
