/*
  Previous - sdlevent.c

  This file is distributed under the GNU General Public License, version 2
  or at your option any later version. Read the file gpl.txt for details.

  This file contains user interface event handling routines.
*/
const char SDLevent_fileid[] = "Previous sdlevent.c";

#include "main.h"
#include "configuration.h"
#include "log.h"
#include "event.h"
#include "keymap.h"
#include "screen.h"
#include "shortcut.h"
#include "sdlgui.h"
#include "sdlkeymap.h"
#include "sdlscreen.h"
#include "sdlstatusbar.h"
#include "dimension.hpp"


static bool bIgnoreNextMouseMotion = false; /* Ignore next mouse motion (needed after SDL_WarpMouse) */

static uint32_t SPECIAL_EVENT;

#ifndef ENABLE_RENDERING_THREAD
/* ----------------------------------------------------------------------- */
/**
 * Save an event and make it available to the emulator thread.
 **/
#define MAX_EVENTS  16
static SDL_Event    mainEvent[MAX_EVENTS];
static SDL_SpinLock mainEventLock;
static int          mainEventWrite;
static int          mainEventRead;
static int          mainEventNext;

/* ----------------------------------------------------------------------- */
/**
 * Initialize event queue.
 **/
void GuiEvent_InitEventQueue(void) {
	mainEventRead = mainEventWrite = 0;
}

/* ----------------------------------------------------------------------- */
/**
 * Save an event. Called from main loop.
 **/
static void GuiEvent_PutEventQueue(SDL_Event* event) {
	if (!bEmulationActive)
		return;

	SDL_LockSpinlock(&mainEventLock);
	mainEventNext = mainEventWrite + 1;
	if (mainEventNext >= MAX_EVENTS) {
		mainEventNext = 0;
	}
	if (mainEventNext == mainEventRead) {
		Log_Printf(LOG_WARN, "Events queue overflow!");
	} else {
		mainEvent[mainEventWrite] = *event;
		mainEventWrite = mainEventNext;
	}
	SDL_UnlockSpinlock(&mainEventLock);
}

/* ----------------------------------------------------------------------- */
/**
 * Get saved event. Called from emulator thread.
 **/
static bool GuiEvent_GetEventQueue(SDL_Event* event) {
	bool valid = false;

	SDL_LockSpinlock(&mainEventLock);
	if (mainEventWrite != mainEventRead) {
		mainEventNext = mainEventRead + 1;
		if (mainEventNext >= MAX_EVENTS) {
			mainEventNext = 0;
		}
		*event = mainEvent[mainEventRead];
		valid = true;
		mainEventRead = mainEventNext;
	}
	SDL_UnlockSpinlock(&mainEventLock);

	return valid;
}

void GuiEvent_EventQueueHandler(void) {
	SDL_Event event;

	if (GuiEvent_GetEventQueue(&event)) {
		switch (event.type) {
			case SDL_EVENT_MOUSE_MOTION:
				Keymap_MouseMove(event.motion.xrel, event.motion.yrel);
				break;
			case SDL_EVENT_MOUSE_BUTTON_DOWN:
				Keymap_MouseDown(event.button.button == SDL_BUTTON_LEFT);
				break;
			case SDL_EVENT_MOUSE_BUTTON_UP:
				Keymap_MouseUp(event.button.button == SDL_BUTTON_LEFT);
				break;
			case SDL_EVENT_MOUSE_WHEEL:
				Keymap_MouseWheel(&event.wheel);
				break;
			case SDL_EVENT_KEY_DOWN:
				Keymap_KeyDown(&event.key);
				break;
			case SDL_EVENT_KEY_UP:
				Keymap_KeyUp(&event.key);
				break;
			default:
				break;
		}
	}
}
#endif /* !ENABLE_RENDERING_THREAD */

/* ----------------------------------------------------------------------- */
/**
 * Initialize special event.
 **/
void GuiEvent_InitSpecialEvent(void) {
	SPECIAL_EVENT = SDL_RegisterEvents(1);
}

/* ----------------------------------------------------------------------- */
/**
 * Send special events. Called from emulator threads.
 **/
void GuiEvent_SendSpecialEvent(int type) {
	SDL_Event event;
	event.type = SPECIAL_EVENT;
	event.user.code = type;
	SDL_PushEvent(&event);
}


/* ----------------------------------------------------------------------- */
/**
 * Set flag to ignore the mouse event that is generated by SDL_WarpMouse().
 */
void GuiEvent_WarpMouse(void) {
	bIgnoreNextMouseMotion = true;
}

/* ----------------------------------------------------------------------- */
/**
 * Handle mouse motion event.
 */
static void GuiEvent_HandleMouseMotion(SDL_Event *pEvent) {
	static SDL_Event mouse_event[100];

	int i, nEvents;

	static float fSavedDeltaX = 0.0;
	static float fSavedDeltaY = 0.0;

	float fDeltaX;
	float fDeltaY;
	int   nDeltaX;
	int   nDeltaY;

	float fExp = bGrabMouse ? ConfigureParams.Mouse.fExpSpeedLocked : ConfigureParams.Mouse.fExpSpeedNormal;
	float fLin = bGrabMouse ? ConfigureParams.Mouse.fLinSpeedLocked : ConfigureParams.Mouse.fLinSpeedNormal;

	if (bIgnoreNextMouseMotion) {
		bIgnoreNextMouseMotion = false;
		return;
	}

	fDeltaX = pEvent->motion.xrel;
	fDeltaY = pEvent->motion.yrel;

	/* Get all mouse event to clean the queue and sum them */
	nEvents = SDL_PeepEvents(mouse_event, 100, SDL_GETEVENT, SDL_EVENT_MOUSE_MOTION, SDL_EVENT_MOUSE_MOTION);

	for (i = 0; i < nEvents; i++) {
		fDeltaX += mouse_event[i].motion.xrel;
		fDeltaY += mouse_event[i].motion.yrel;
	}

	if ((fDeltaX != 0.0) || (fDeltaY != 0.0)) {
		/* Exponential adjustmend */
		if (fExp != 1.0) {
			fDeltaX = (fDeltaX < 0.0) ? -pow(-fDeltaX, fExp) : pow(fDeltaX, fExp);
			fDeltaY = (fDeltaY < 0.0) ? -pow(-fDeltaY, fExp) : pow(fDeltaY, fExp);
		}

		/* Linear adjustment */
		if (fLin != 1.0) {
			fDeltaX *= fLin;
			fDeltaY *= fLin;
		}

		/* Add residuals */
		if ((fDeltaX < 0.0) == (fSavedDeltaX < 0.0)) {
			fSavedDeltaX += fDeltaX;
		} else {
			fSavedDeltaX  = fDeltaX;
		}
		if ((fDeltaY < 0.0) == (fSavedDeltaY < 0.0)) {
			fSavedDeltaY += fDeltaY;
		} else {
			fSavedDeltaY  = fDeltaY;
		}

		/* Convert to integer and save residuals */
		nDeltaX = (int)fSavedDeltaX;
		nDeltaY = (int)fSavedDeltaY;
		fSavedDeltaX -= (float)nDeltaX;
		fSavedDeltaY -= (float)nDeltaY;

		/* Done */
#ifdef ENABLE_RENDERING_THREAD
		Keymap_MouseMove(nDeltaX, nDeltaY);
#else
		pEvent->motion.xrel = nDeltaX;
		pEvent->motion.yrel = nDeltaY;

		GuiEvent_PutEventQueue(pEvent);
#endif
	}
}

/* ----------------------------------------------------------------------- */
/**
 * Sends key up events for all currently pressed keys.
 */
void GuiEvent_ResetKeys(void) {
	SDL_Event event;

	SDL_ResetKeyboard();

	/* Send magic key sequence to avoid stuck keys */
	event.type         = SDL_EVENT_KEY_DOWN;
	event.key.scancode = SDL_SCANCODE_LCTRL;
	event.key.key      = SDLK_LCTRL;
	event.key.mod      = SDL_KMOD_LCTRL;
	SDL_PushEvent(&event);

	if (ConfigureParams.System.bADB) {
		event.type         = SDL_EVENT_KEY_UP;
		event.key.scancode = SDL_SCANCODE_LCTRL;
		event.key.key      = SDLK_LCTRL;
		event.key.mod      = SDL_KMOD_LCTRL;
		SDL_PushEvent(&event);
	}

	event.type         = SDL_EVENT_KEY_UP;
	event.key.scancode = SDL_SCANCODE_Q;
	event.key.key      = SDLK_Q;
	event.key.mod      = SDL_KMOD_NONE;
	SDL_PushEvent(&event);
}

/* ----------------------------------------------------------------------- */
/**
 * Is a shortcut modifier key pressed?
 */
static bool GuiEvent_ShortcutMod(int modkey)
{
	return (modkey & SDL_KMOD_CTRL) && (modkey & SDL_KMOD_ALT);
}


/* ----------------------------------------------------------------------- */
/**
 * SDL message handler.
 * Here we process the SDL events (keyboard, mouse, ...)
 */
void GuiEvent_EventHandler(void) {
	bool bContinueProcessing;
	SDL_Event event;
	bool events;

	do {
		bContinueProcessing = false;

#ifdef ENABLE_RENDERING_THREAD
		if (bEmulationActive) {
			events = SDL_PollEvent(&event);
		} else {
			events = SDL_WaitEvent(&event);
		}
#else
		events = SDL_WaitEventTimeout(&event, 100);
#endif
		if (!events) {
			/* no events -> if emulation is active or
			 * user is quitting -> return from function.
			 */
			continue;
		}
		switch (event.type) {
			case SDL_EVENT_WINDOW_CLOSE_REQUESTED:
				SDL_FlushEvent(SDL_EVENT_QUIT); /* Remove quit event if pending */
				Main_RequestQuit(true);
				continue;

			case SDL_EVENT_WINDOW_RESIZED:
				Screen_SizeChanged();
				continue;

			case SDL_EVENT_QUIT:
				Main_RequestQuit(true);
				break;

			case SDL_EVENT_MOUSE_MOTION:               /* Read/Update internal mouse position */
				GuiEvent_HandleMouseMotion(&event);
				bContinueProcessing = false;
				break;

			case SDL_EVENT_MOUSE_BUTTON_DOWN:
				if (ConfigureParams.Mouse.bEnableMacClick) {
					if (event.button.button == SDL_BUTTON_LEFT) {
						if (SDL_GetModState() & SDL_KMOD_CTRL) {
							event.button.button = SDL_BUTTON_RIGHT;
						}
					}
				}
				if (event.button.button == SDL_BUTTON_LEFT) {
					if (ConfigureParams.Mouse.bEnableAutoGrab) {
						if (bGrabMouse) {
							if (SDL_GetModState() & SDL_KMOD_CTRL) {
								bGrabMouse = false;
								Screen_SetMouseGrab(bGrabMouse);
								break;
							}
						} else {
							bGrabMouse = true;
							Screen_SetMouseGrab(bGrabMouse);
							break;
						}
					}
#ifdef ENABLE_RENDERING_THREAD
					Keymap_MouseDown(true);
#else
					GuiEvent_PutEventQueue(&event);
#endif
				}
				else if (event.button.button == SDL_BUTTON_RIGHT)
				{
#ifdef ENABLE_RENDERING_THREAD
					Keymap_MouseDown(false);
#else
					GuiEvent_PutEventQueue(&event);
#endif
				}
				break;

			case SDL_EVENT_MOUSE_BUTTON_UP:
				if (ConfigureParams.Mouse.bEnableMacClick) {
					if (event.button.button == SDL_BUTTON_LEFT) {
						if (SDL_GetModState() & SDL_KMOD_CTRL) {
							event.button.button = SDL_BUTTON_RIGHT;
						}
					}
				}
				if (event.button.button == SDL_BUTTON_LEFT) {
#ifdef ENABLE_RENDERING_THREAD
					Keymap_MouseUp(true);
#else
					GuiEvent_PutEventQueue(&event);
#endif
				}
				else if (event.button.button == SDL_BUTTON_RIGHT)
				{
#ifdef ENABLE_RENDERING_THREAD
					Keymap_MouseUp(false);
#else
					GuiEvent_PutEventQueue(&event);
#endif
				}
				break;

			case SDL_EVENT_MOUSE_WHEEL:
#ifdef ENABLE_RENDERING_THREAD
				Keymap_MouseWheel(&event.wheel);
#else
				GuiEvent_PutEventQueue(&event);
#endif
				break;

			case SDL_EVENT_KEY_DOWN:
				if (event.key.repeat) {
					break;
				}
				if (ShortCut_CheckKeys(event.key.key, GuiEvent_ShortcutMod(event.key.mod), true)) {
					ShortCut_ActKey();
					break;
				}
#ifdef ENABLE_RENDERING_THREAD
				Keymap_KeyDown(&event.key);
#else
				GuiEvent_PutEventQueue(&event);
#endif
				break;

			case SDL_EVENT_KEY_UP:
				if (ShortCut_CheckKeys(event.key.key, GuiEvent_ShortcutMod(event.key.mod), false)) {
					break;
				}
#ifdef ENABLE_RENDERING_THREAD
				Keymap_KeyUp(&event.key);
#else
				GuiEvent_PutEventQueue(&event);
#endif
				break;

			default:
				/* check special remote events */
				if (event.type == SPECIAL_EVENT) {
					switch (event.user.code) {
						case SPECIAL_EVENT_PAUSE:
							Main_PauseEmulation(false);
							break;
						case SPECIAL_EVENT_UNPAUSE:
							Main_UnPauseEmulation();
							break;
#ifndef ENABLE_RENDERING_THREAD
						case SPECIAL_EVENT_REPAINT:
							Statusbar_Update(sdlscrn);
							Screen_Repaint();
							break;
						case SPECIAL_EVENT_ND_DISPLAY:
							nd_display_repaint();
							break;
						case SPECIAL_EVENT_HALT:
							Main_HaltDialog();
							break;
#endif
						default:
							break;
					}
					break;
				}
				/* don't let unknown events delay event processing */
				bContinueProcessing = true;
				break;
		}
	} while (bContinueProcessing || !(bEmulationActive || bQuitProgram));
}


void UI_Init(void) {
	/* Needed on maemo but useful also with normal X11 window managers for
	 * window grouping when you have multiple Previous SDL windows open */
	SDL_SetAppMetadataProperty(SDL_PROP_APP_METADATA_IDENTIFIER_STRING, "com.sourceforge.previous");

	/* Init SDL's video subsystem. Note: Audio subsystem
	   will be initialized later (failure not fatal). */
	if (SDL_Init(SDL_INIT_VIDEO) == false)
	{
		Main_ErrorExit("Could not initialize the SDL library:", SDL_GetError(), -1);
	}
	SDLGui_Init();
	Screen_Init();
	Keymap_Init();
}

void UI_UnInit(void) {
	SDLGui_UnInit();
	Screen_UnInit();

	/* SDL uninit: */
	SDL_Quit();
}
